 GET  http://localhost:3000/api/contacts/


 ###

 PUT  http://localhost:3000/api/contacts/

   {
    "id": 4,
    "fullName": "willian",
    "phoneNumber": 8096656366,
    "email": "carlos.sanchez@example.com"
  }